const API = {
    baseurl: process.env.REACT_APP_BASE_URL,
    // baseurl: "http://3.15.28.195:15355/api/",
    imageurl: process.env.REACT_APP_IMAGES_URL,
    // imageurl: "http://3.15.28.195/",
    productionurl : process.env.REACT_APP_PRODUCTION_URL,
    // productionurl : "http://3.15.28.195/", //"http://193.46.199.249/",
    // Ravi added
    // Admin Routes //
    add_category : "admin/category",
    get_categories : "/category",
    del_category : "admin/category/",
    get_categoryinfo : "category/",
    put_category : "admin/category/",

    add_question : "admin/question",
    get_question : "question",
    del_question : "admin/question/",

    add_subcategory : "admin/subcategory",
    get_subcategory : "/subcategory",
    get_subcategoryinfo : "subcategory/",
    del_subcategory : "admin/subcategory/",

    get_contactinfo : "admin/getAdminSettings",
    update_adminsettings : "admin/updateAdminSettings",

    // Admin Routes Closed //

    // Frontend routes
    login : "login",
    customersignup : "registration",
    getSubCategoryByCategory : "getSubCategoryByCategory",
    questionBySubcat : "questionBySubcat",
    addTask : "task",
    getOpenTaskList : "tasks?page=1&type=Open",
    getUserInfo : "authUserInfo",
    updateUserAccount : "updateProfile",
    updateUserBilling : "updateBillingDetail",
    changePasswordAuth : "changeAuthPassword",
    getFavouriteProviders : "getFavoriteProvider",
    getNotifications : "getNotificationList",
    submitQuery : "querise",
    changePasswordByToken : "changePasswordByToken",
    getBusinessList : "business",
    getBusinessInfo : "business/",
    getBusinessReviews : "getBusinessReviews/", //?pagesize=1&page=1",
    getBusinessRating : "getBusinessRatings/",
    changeUserRole : "changeAuthType",
    taskInterestedProvider : 'interestedProvider',
    getLeads : "getProviderLeads",
    deleteBusiness : "business/",
    updateProfileImage : "updateProfileImage",
    megamenuData : "subcategorygroup",
    providersListbySubcategory : "providerBySubCategory",
    providersListbyCategory : "providerByCategory",
    updateBusinessInfo : "updateBusinessInfo/",
    resendOTP : "phoneOtpRequest",
    verifyOTP : "phoneOtpValidation",
    verifyEmail : "emailVerifiedLink",
    addToFavouriteProvider : "addFavoriteProvider",
    removeFavouriteProvider : "removeFavouriteProvider",
    checkFavoriteProvider : "checkFavoriteProvider",
    purchaseTask: "purchasedTask",
    acceptQuoteTask: "acceptQuoteTask",
    rejectQuoteTask: "rejectQuoteTask",
    getCreditPoints : "credits",
    purchaseCreditPoints : 'purchasePoint',
    MyTaskList : "myTaskList", //?pagesize=10&page=1
    unsuccessfulTaskProviders : "unsuccessfulTaskProviders",


      //aaqib side
      phoneOtpValidation: "/phoneOtpValidation",
      forgotPasswordByEmail: "forgotPasswordByEmail",
      changePassword: "/changePassword",
      addBusiness: "/business",
      subCatByParentCat: "/getSubCategoryByCategory",
      businessCategoryUpdate: "businessCategory/",
      businessUploadDemo: "businessUploadDemos/",
      businessUpdateLocation: "businessUpdateLocation/",
      writeAReview: "writeAReview/",
      writeTaskReview: "writeTaskReview/",
      referralBonusEmail: "referralBonusEmail",
      taskQuotation: "taskQuotation",
      businessList: "business",
      getProviderLeads: "getProviderLeads",
      subcategorygroup: "subcategorygroup",
      taskCategoryWise: "taskCategoryWise",
      taskSubCategoryWise: "taskSubCategoryWise",
      businessReviews: "businessReviews",
      bookedTasks: "myTaskList",
      canceltask: "canceltask",
      // createInvoice: "createInvoice",
      taskInfo: "task/",
      getBalancePoints: "getBalancePoints",
      paymentTransectionList: "paymentTransectionList",
      paymentTransactionDetail: "paymentTransectionDetail",
      declinetask: "declinetask",
      getsupportInfo: "getsupportInfo",
      getCustomerFaqs: "getCustomerFaqs",
      //admin
      adminCategorylist: "admin/categorylist",
      adminCustomerlist: "admin/customerlist",
      admincustomerinfo: "admin/customerinfo",
      delCat: "admin/customerdelete/",
      customercreate: "admin/customercreate",
      customerupdate: "admin/customerupdate/",
      providerlist: "/admin/providerlist",
      provDelete: "admin/providerdelete/",
      createProvider: "admin/providercreate",
      updateProvider: "admin/providerupdate/",
      adminTasklist: "admin/tasklist/",
      adminTaskInfo: "admin/taskinfo/",
      adminTaskDelete: "admin/taskdelete/",
      transactionlist: "admin/transactionlist",
      transactionDelete: "admin/transaction/",
      adminContactInfo:  "admin/getAdminSetting",
      updateAdminSetting:  "admin/updateAdminSetting",
      //admin
      //aaqib

    // Ajay Addedd
    getProviderNewLead : "getProviderNewLead",
    getProviderPurchasedLead : "getProviderPurchasedLead",
    getProviderClosedLead : "getProviderClosedLead",
    getProviderRequestedLead : "getProviderRequestedLead",
    createInvoice : "provider/createInvoice",
    responseReviews: "provider/responseReviews",
    // Admin QuestionList //
    adminQuestionlist : "admin/questionlist",
    adminQuestionInfo : "admin/questioninfo/",
    adminQuestioUpdate : "admin/question/",
    // Admin Sub Categories //
    adminSubcategorylist : "admin/subcategorylist",
    adminSubcategoryInfo : "admin/subcategoryinfo/",
    adminSubcategoryUpdate : "admin/subcategory/",
  };
  
  export default API;
  